-- MySQL Script generated by MySQL Workbench
-- Tue May  2 11:33:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema diplom
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema diplom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `diplom` DEFAULT CHARACTER SET utf8 ;
USE `diplom` ;

-- -----------------------------------------------------
-- Table `diplom`.`admins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`admins` (
  `id_admins` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(35) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_admins`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplom`.`personals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`personals` (
  `id_personals` INT NOT NULL AUTO_INCREMENT,
  `parent` INT NOT NULL,
  `login` VARCHAR(35) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `data_created` DATE NOT NULL,
  PRIMARY KEY (`id_personals`, `parent`),
  INDEX `fk_personals_admins1_idx` (`parent` ASC) VISIBLE,
  CONSTRAINT `fk_personals_admins1`
    FOREIGN KEY (`parent`)
    REFERENCES `diplom`.`admins` (`id_admins`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplom`.`consistent_circuit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`consistent_circuit` (
  `id_consistent_circuit` INT NOT NULL AUTO_INCREMENT,
  `f_list_consistens` JSON NOT NULL,
  `z_list` JSON NOT NULL,
  `phi_list` JSON NOT NULL,
  PRIMARY KEY (`id_consistent_circuit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplom`.`parallel_circuit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`parallel_circuit` (
  `id_parallel_circuit` INT NOT NULL AUTO_INCREMENT,
  `f_list_parallel` JSON NOT NULL,
  `gp_list` JSON NOT NULL,
  `rp_list` JSON NOT NULL,
  `cp_list` JSON NOT NULL,
  PRIMARY KEY (`id_parallel_circuit`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `diplom`.`parameters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `diplom`.`parameters` (
  `id_parameters` INT NOT NULL AUTO_INCREMENT,
  `worker_personal` INT NOT NULL,
  `description` TEXT NOT NULL,
  `z_only` TINYINT NOT NULL,
  `id_consistent_circuit` INT NULL,
  `id_parallel_circuit` INT NULL,
  PRIMARY KEY (`id_parameters`, `worker_personal`),
  INDEX `fk_parameters_personals1_idx` (`worker_personal` ASC) VISIBLE,
  INDEX `fk_parameters_consistent_circuit1_idx` (`id_consistent_circuit` ASC) VISIBLE,
  INDEX `fk_parameters_parallel_circuit1_idx` (`id_parallel_circuit` ASC) VISIBLE,
  CONSTRAINT `fk_parameters_personals1`
    FOREIGN KEY (`worker_personal`)
    REFERENCES `diplom`.`personals` (`id_personals`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parameters_consistent_circuit1`
    FOREIGN KEY (`id_consistent_circuit`)
    REFERENCES `diplom`.`consistent_circuit` (`id_consistent_circuit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_parameters_parallel_circuit1`
    FOREIGN KEY (`id_parallel_circuit`)
    REFERENCES `diplom`.`parallel_circuit` (`id_parallel_circuit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
